import "./globals.scss";
import type { Metadata } from "next";

import { futuraBk, futuraMd, futuraHV } from "@/fonts/index";

export const metadata: Metadata = {
  title: "Poliescol",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${futuraBk.className} ${futuraMd.variable} ${futuraHV.variable} body`}
      >
        {children}
      </body>
    </html>
  );
}
