import "./globals.scss";
import type { Metadata } from "next";

import clsx from "clsx";

import { futuraBk, futuraLt, futuraMd, futuraHV } from "@/fonts/index";

export const metadata: Metadata = {
  title: "Poliescol",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={clsx(
          "body",
          futuraBk.className,
          futuraLt.variable,
          futuraMd.variable,
          futuraHV.variable
        )}
      >
        {children}
      </body>
    </html>
  );
}
